/*
  # SMS Verification System

  1. New Tables
    - `tmp_otp_trigger`
      - `id` (bigint, primary key)
      - `code` (bigint, not null) - The OTP code
      - `user_id` (uuid, not null) - Reference to auth.users
      - `phone` (text, not null) - User's phone number
      - `confirmation_token` (text, not null) - Token for verification
      - `created_at` (timestamptz) - When OTP was created
      - `expires_at` (timestamptz) - When OTP expires

  2. Functions
    - `trigger_otp()` - Generates and stores OTP when user requests verification

  3. Triggers
    - `trigger_otp` - Executes on auth.users table updates
*/

-- Create temporary OTP storage table
CREATE TABLE IF NOT EXISTS public.tmp_otp_trigger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code bigint NOT NULL,
  user_id uuid NOT NULL,
  phone text NOT NULL,
  confirmation_token text NOT NULL,
  created_at timestamptz DEFAULT now(),
  expires_at timestamptz DEFAULT (now() + interval '5 minutes')
);

-- Enable RLS
ALTER TABLE public.tmp_otp_trigger ENABLE ROW LEVEL SECURITY;

-- Create OTP trigger function
CREATE OR REPLACE FUNCTION trigger_otp()
RETURNS TRIGGER
AS $$
DECLARE 
  otp bigint;
BEGIN
    IF OLD.confirmation_token = NEW.confirmation_token THEN
      RETURN NEW;
    END IF;
    
    IF NEW.confirmation_token = '' THEN
      RETURN NEW;
    END IF;
    
    -- Generate 6-digit OTP
    otp := FLOOR(RANDOM() * 900000 + 100000);
    
    -- Store OTP with user details
    INSERT INTO public.tmp_otp_trigger (
      code, 
      user_id, 
      phone, 
      confirmation_token
    ) 
    VALUES (
      otp, 
      NEW.id, 
      NEW.phone, 
      NEW.confirmation_token
    );
    
    -- Hash phone+OTP for verification
    NEW.confirmation_token := encode(sha224(concat(NEW.phone,otp)::bytea), 'hex');
    NEW.confirmation_sent_at := now();
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger
DROP TRIGGER IF EXISTS trigger_otp ON auth.users;
CREATE TRIGGER trigger_otp 
  BEFORE INSERT OR UPDATE ON auth.users 
  FOR EACH ROW 
  EXECUTE PROCEDURE trigger_otp();

-- Add policies for OTP table
CREATE POLICY "Users can read their own OTP records"
  ON public.tmp_otp_trigger
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- Add cleanup function for expired OTPs
CREATE OR REPLACE FUNCTION cleanup_expired_otps()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.tmp_otp_trigger
  WHERE expires_at < now();
END;
$$;